site_name: Frogwatch Handleiding
site_description: Handleiding voor het Frogwatch Trillingsmeter platform
site_author: Jitter

nav:
    - Home: index.md
    - Veiligheidsinformatie: safety.md
    - Getting Started: gettingstarted.md
    - Frogwatch V1:
      - safety-v1.md
      - hardware-v1.md
      - battery-v1.md
      - charger-v1.md
      - adapter-12v.md
      - ce-info-v1.md
    - Frogwatch V2:
      - safety-v2.md
      - hardware-v2.md
      - battery-v2.md
      - charger-v2.md
      - adapter-12v.md
      - ce-info-v2.md
    - Dashboard: dashboard.md
    - Frogwatch USB: usb.md
    - Kalibratie: kalibratie.md
    - FAQ: faq.md
    - About: about.md

theme:
  features:
    - navigation.indexes
  name: readthedocs
  prev_next_buttons_location: bottom
  custom_dir: custom_theme/
extra_css: [extra.css]

docs_dir: docs
